# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_is_donor', models.NullBooleanField(default=None)),
                ('support_is_periodical', models.NullBooleanField(default=None)),
                ('support_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('support_payment_response', models.TextField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
